# fly.toml app configuration file generated for pseudogen-frontend on 2026-02-09T16:38:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pseudogen-frontend'
primary_region = 'iad'

[build]

[env]
  BACKEND_URL = 'https://pseudogen-backend.fly.dev'
  BACKEND_HOST = 'pseudogen-backend.fly.dev'
  PORT = '80'

[http_service]
  internal_port = 80
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
